models/awp_rooms/3_baril_empliler.mdl
models/awp_rooms/bags1_da.mdl
models/awp_rooms/Barrel2.mdl
models/awp_rooms/chair1_da.mdl
models/awp_rooms/chair2_da.mdl
models/awp_rooms/crate1_da.mdl
models/awp_rooms/doorrollup1_da.mdl
models/awp_rooms/doorrollup2_da.mdl
models/awp_rooms/ebox1_da.mdl
models/awp_rooms/electricbox2.mdl
models/awp_rooms/fence1_da.mdl
models/awp_rooms/Generator6.mdl
models/awp_rooms/Gibs1.mdl
models/awp_rooms/Gibs10.mdl
models/awp_rooms/Gibs2.mdl
models/awp_rooms/Gibs3.mdl
models/awp_rooms/Gibs4.mdl
models/awp_rooms/Gibs5.mdl
models/awp_rooms/Gibs7.mdl
models/awp_rooms/Gibs9.mdl
models/awp_rooms/LightFixture8.mdl
models/awp_rooms/oil02.mdl
models/awp_rooms/pc1_da.mdl
models/awp_rooms/pillar1_da.mdl
models/awp_rooms/table3_da.mdl
models/awp_rooms/vent1_da.mdl
models/awp_rooms/Vent7.mdl
models/awp_rooms/welectcric.mdl
models/awp_rooms/wire1_da.mdl
models/awp_rooms/wire2_da.mdl
sprites/awp_rooms/Glow8.spr